### PR TITLE
Import psutil conditionally; install it only in Linux platforms

### PR DESCRIPTION
**Pull request by gfrances**
See #99 for the rationale to this PR

### CODE REVIEW

**Comment by miquelramirez** [comment]
Looks good Guillem :+1:

**Comment by gfrances** [comment]
Yes, but they seem related to some code in a previous commit by @miquelramirez (easy to see the first failing commit [here](https://github.com/aig-upf/tarski/commits/devel)).
@miquelramirez , do you think this is fixable? Or maybe I could move the NDL-related commits to a diff branch (they seem pretty self-contained, but I've only given a quick glance)?

**Comment by miquelramirez** [comment]
Cheers for the heads up, it's a trivial issue, will fix soon.

**Comment by miquelramirez** [comment]
Should be fixed with commit b4be590ba4dfa5b05d8b11b5a2685fbeef4c5383

**Pull request merged**
