### PR TITLE
Universal and conditional effects

### PR DESCRIPTION
**Pull request by emilkeyder**
Add universal and conditional effects.

### CODE REVIEW

**Comment by miquelramirez** [comment]
Cheers @emilkeyder, I will get back to you in a couple days

**Comment by emilkeyder** [comment]
I'm confused by the errors - when I run locally the test passes, and what it's complaining about is something I had to fix previously (extra whitespace in the assertion of what the printed effect looks like). Anyway let me know if I'm missing something obvious or there are some changes I should make to fix it.

**Comment by miquelramirez** [comment]
Hi @emilkeyder,

looked at this a little bit today before getting pulled into other stuff and I am also a bit surprised by the tests failing. I will look into it for real tonight, when the girls are all asleep,

Miquel

**Comment by miquelramirez** [comment]
Okay, not sure what was the issue - perhaps your git client is very aggressive handling changes in whitespace of files?

**Pull request merged**
