### PR TITLE
Be consistent in FSTRIPS hierarchy attributes: `symbol`, `name`, `head`

### PR DESCRIPTION
**Pull request by gfrances**
This is a spin-off from #53: we want to be more consistent in the way we name attributes in different classes of the FSTRIPS hierarchy. Quoting a couple of comments from that issue:

> - [x]  in one of them the main attribute is called `symbol`, whereas in the other it's `_symbol`, and then a `@property` is there to help make things uniform. This "symbol" is sometimes a string, sometimes an object of type BuiltinSymbol, etc.

> - [x]  I see that you haven't transformed all terms yet (constants have a `symbol` not a `name`), and that there's now a new member called `head` defined for all `CompoundTerms` (but the subclasses haven't been changed).

> - [x]  The general rationale for changing symbol to name was to call "symbol" those attributes that are indeed a symbol (i.e. a function symbol or a predicate symbol); and call "name" those attributes that are just strings or literals. OTOH, the rationale for changing the interface of CompoundTerms was to have both CompoundTerm and Atom present the same interface (a head plus a number of subterms).

I've done a few renamings, following the ideas below. Of course they are open to discussion. This will likely break things in client projects, maybe also in untested regions of the code in this project, so the sooner, the better :-)

@miquelramirez, I'd leave this open until you find some time to (1) review the 3 guidelines below and confirm you're happy with them, and only then, (2) check in your client projects how much they break things, and if you're happy with refactoring that.

**Naming conventions**:
1. We call `symbol` those attributes that are either a function or a predicate symbol, meaning that they are an object of the corresponding Python class (`FunctionSymbol`, `PredicateSymbol`)
    * In particular, for compound expressions (such as `Atoms`, `CompoundTerms`) of the form `f(x1, ..., xn)`, we call `f` the `symbol`, and the list `<x1, ..., xn>`, we call `subterms` (could call them perhaps `arguments`, no clear preference between the two). This seems to me quite FOL-like: an atom is a predicate symbol paired with as terms as its arity, etc.
1. We call `name` those attributes which are a Python literal (typically string, occasionally int, float).
    * In particular, this includes the attribute `name` of PredicateSymbols and FunctionSymbols, as well as of Constants and other terms.
1. No more attributes called `head` - their usage is similar to "symbol" above

### CODE REVIEW

**Comment by miquelramirez** [comment]
One of the most common use cases I have in client projects that compile formulas and expressions is that depending on the type and value of the attribute `symbol` we decide to translate in a particular way. I am not sure if I am "happy" to refactor code just make a point to myself that an object of type `int` has a `name` but an object of type `function` has a `symbol`. 

What are the practical advantages of making this distinction?

**Comment by gfrances** [comment]
> I am not sure if I am "happy" to refactor code just make a point to myself that an object of type `int` has a `name` but an object of type `function` has a `symbol`.

Not sure I follow here. Let me explain the purpose of the PR. In the PR, a function symbol is now represented by objects of class `FunctionSymbol` (not `Function` anymore). This is to keep the standard FOL nomenclature: a function is one thing (belonging to the semantic level); a function symbol is another (belonging to the syntactic level). This said, a `FunctionSymbol` contains an attribute `name` that is the string itself. Calling that attribute `symbol` as we were doing before leads to some confusion (i.e. one would expect an attribute `symbol` to be an object of the symbol class), and (less important), to some ugly expressions such as `expr.symbol.symbol`. OTOH, it is not the case that "an object of type `int` has a `name`". In the PR, objects of type `Constant` have an attribute `name` that is tipically a string, such as "block1", etc. We could perhaps call this attribute `value`, but I think it's good to keep it in sync with the nomenclature of class `FunctionSymbol`, since, after all, in FOL a constant is a function symbol.

The whole point of the PR is thus to have some naming consistency. I admit the practical advantages of refactoring working code for this are not huge, but looking forward, it's always good to have solid naming conventions. Hopefully, the renaming effort shouldn't be terrible, but of course it's always some work. Let me know your opinion, I wouldn't be terribly opposed to dropping the PR if you insist.

BTW just realized some changes to the DL module made into this PR inadvertently (my bad, this branch stayed around for too long). I should port them separately to the dev branch if we drop the PR altogether, just a note to myself.

**Comment by miquelramirez** [comment]
The comment means what it says. I just do not see what is the tangible benefit of the proposed change and wanted to see the full argument.  Now we do

```
value = S[expr].symbol
```
and now needs to be changed on case by case basis. This is not a change I can automate easily. 

In any case I would prefer `value` over `name`, as if we have a `Constant` of a `Sort` called `int` I find strange to think of "42" as a "name".

**Comment by gfrances** [comment]
What would need to be changed on a case-by-case basis exactly? If I understand correctly, any expression of the type `model[someterm].symbol` will evaluate to a constant, which will have an attribute `name`, or `value`, whichever we choose. But what would be the other case? I don't think such an expression could result in a Predicate, or in a Function, or am I missing something

**Comment by miquelramirez** [comment]
Hi @gfrances,

we can get a predicate or function if there are terms without values associated. This is most commonly an oversight and needs to be reported with a meningful exception.

Regards,

Miquel.

**Comment by miquelramirez** [comment]
Also, I don't quite understand the conflict reported by github

```Python
    def get_functions(self):
        res = []
        for fun in self.lang.functions:
            if fun.builtin:
                continue  # Don't declare builtin elements
            domain_str = build_signature_string(fun.domain)
<<<<<<< dev-0.2.0-symbols
            codomain_str = tarsky_to_pddl_type(fun.codomain)
            res.append("({} {}) - {}".format(fun.name, domain_str, codomain_str))
=======
            codomain_str = tarski_to_pddl_type(fun.codomain)
            res.append("({} {}) - {}".format(fun.symbol, domain_str, codomain_str))
>>>>>>> dev-0.2.0
        return ("\n" + _TAB * 2).join(res)
```

How come the code is compliant in `dev-0.2.0` but not compliant with this change in `dev-0.2.0-symbols`?

**Comment by gfrances** [comment]
Yes, that typo correction (tarsky to tarski) seems to have created some merge conflicts in other branches as well, not sure why (for instance, in the example you mention, the changes are on adjacent lines, but not in the same line). But should be mergeable anyway with a bit more effort.

But going to your previous comment: so you say that we can have a situation where the result of evaluating an expression on a `Model ` (through the `[]` operator, for instance) can be a predicate or a function symbol? That sounds strange to me... do you have in mind some example or test where I can see how that works?

**Comment by miquelramirez** [comment]
> But going to your previous comment: so you say that we can have a situation where the result of evaluating an expression on a Model (through the [] operator, for instance) can be a predicate or a function symbol? That sounds strange to me... do you have in mind some example or test where I can see how that works?

In one of my research projects I have a constraint which looks like this:

```
vx(o)^2 + wx()^2
```

under certain circumstances, _wx()_ is a map to a _single_ constant value, _k_ and under certain other circumstances _wx()_ value is not constant, but changes over time. When I evaluate the expression, then I get either ```vx(o)^2 + k^2``` or ```vx(o)^2 + wx()^2```. Then I calculate the Jacobian - the derivatives with respect every variable - and I get two very different results.

**Comment by gfrances** [comment]
That sounds fine - from a logical perspective, `wx` is a function symbol; and `vx(o)^2 + wx()^2` is a term. Evaluating that term under a first-order structure should result in some element in the universe - which in our case, with our slightly hackyish approach, we represent as a Python object of type `Constant`.  But from what you say, it seems that the operation of evaluating the term on a structure yields another term? If that is the case, perhaps that should be represented not as term evaluation, but rewriting / simplification, or some other operation?

**Comment by miquelramirez** [comment]
> But from what you say, it seems that the operation of evaluating the term on a structure yields another term? If that is the case, perhaps that should be represented not as term evaluation, but rewriting / simplification, or some other operation?

When evaluating terms which are arithmetic expressions I am making sure that we're following the typical conventions in arithmetics. Which is that you **evaluate** an expression - a well formed arithmetic formula combining functions, algebraic symbols and operators - you end up with another expression. That result can be a constant if all the functions are bound to values, or a composite arithmetic expression as in the example.

As part of the evaluation procedure there are simplification steps too - see the simplify() function in tarski/arithmetics for instance. That is indeed a limited form of term rewriting, as we seek the most succinct equivalent arithmetic formula. It is also an standard feature in algebraic computing systems, like `sympy`. 

Eventually I would like to offload on `sympy` all of this stuff, but I preferred to start with something that was functional yet avoided external dependencies.

**Comment by gfrances** [comment]
I see, thanks for the very clear explanation! I think by all means we have to support this type of functionality. My only quarrel is with the naming - I think we have two different things here: one is computing the denotation of a term in a first-order structure, which results in a member of the universe of that structure. The other one is the evaluation of arithmetic expressions (i.e., the symbolic evaluation of arithmetic expressions), which is the one you describe. From a pure logical perspective, I guess (but might be wrong) that what engines such as SymPy do could be captures by posing as your universe of discourse the infinite set of all possible arithmetic (syntactic) expressions. A bit like a Herbrand structure perhaps? (Should think about this more). But in any case, as you say, this view not too useful for practical purposes.

In any case, I think it'd be good to think about the way in which we name this, and eventually have different names for the two slighly different operations that I mention above. I don't think that that is urgent or even belongs too much to this PR in particular, so no need to pursue that now. 

Insofar as this PR is concerned (`symbol` vs `name`, etc.), do you think it'd be better to close it without merging then? I like the renaming, but didn't expect nor want it to create so many practical trouble, so I'm happy to ditch it and move forward!

**Comment by miquelramirez** [comment]
> Insofar as this PR is concerned (symbol vs name, etc.), do you think it'd be better to close it without merging then? I like the renaming, but didn't expect nor want it to create so many practical trouble, so I'm happy to ditch it and move forward!

Let's keep it in the freezer for the time being. As I am not envisioning to extend Tarski basic structure much for the foreseeable future perhaps this can be reassessed in a different light later on (or after we have integrated ```sympy```).

**Comment by gfrances** [comment]
I'm closing this one for the moment being, as it would likely require a fresh refactoring of the attribute names.

**Pull request closed without merging**
