### PR TITLE
Implement ASP-based grounding and reachability

### PR DESCRIPTION
**Pull request by gfrances**
This PR integrates a working ASP-based grounding & reachability module. The module is a loose port of the code we had in the `fs` planner for this, and includes an interaction with the `Clingo` ASP solver, if found in the system. That is of course optional, we might just be interested in generating the logic program :-)

This is related to #15, #16, #19, #44. Some of those could be closed once we merge this PR.
OTOH, it might break some things related to the standard ("naive") grounding, as I have refactored it a bit.

### CODE REVIEW

**Comment by miquelramirez** [comment]
Before merging the PR, one q uestion for you. Does this supersede naive grounding altogether?

I see all the tests passing, so any problems would indicate incomplete test coverage to be fixed.

**Comment by gfrances** [comment]
It offers LP-based alternatives for the two main "naive grounding" external methods: list ground state variables, and list ground actions for a problem. The difference of course being that the LP-based do a reachability analysis that the naive grounding does not do. That said, I still think that the naive set of strategies could still have its place (e..g,  when the reachability analysis is too expensive, etc., or even only for pedagogic purposes...). What do you think?

**Comment by miquelramirez** [comment]
Yes, you're right that the "naive" it has its niche due to its immediacy, lack of external dependencies and pedagogical value.

I was about to merge the PR but I see now that there's a bunch of conflicts being listed. This looks like a new feature I was not aware of. What would be the merge strategy for this?

**Comment by gfrances** [comment]
oh I see, some typo I corrected, let me take care of this

**Comment by gfrances** [comment]
Ok, that was a bit more than some typos, but it's merged now, hope nothing got broken :-)

**Pull request merged**
